### PR TITLE
Fix : Bug in the count of characters and minutes read [fixes #1]

### LINKED ISSUE #1: Bug in the count of characters and minutes read.
On typing and recording the text , count of characters and time for reading is wrong.

### PR DESCRIPTION
**Pull request by najeebkp**
### Fix : Bug in the count of characters and minutes read [fixes #1]

### CODE REVIEW

**Review by Mitushi-23 — COMMENTED** [review]
In the changes you made only typing text will be considered. As you have removed the recorded text.
So first recheck whether both typing and recorded text are appearing in preview section or not.

**Comment by najeebkp** [comment]
I dint get what is recorded text. can you share a screen recording about that?

**Comment by Mitushi-23** [comment]
> I dint get what is recorded text. can you share a screen recording about that?

In this you have the option to record the text by clicking start button and adding of the notes.
Screenshot (14)

**Comment by najeebkp** [comment]
but im not able to see any recording. these buttons do nothing when i check

**Comment by Mitushi-23** [comment]
> but im not able to see any recording. these buttons do nothing when i check

After clicking start you have to speak something so that it can be recorded.

**Comment by najeebkp** [comment]
please check it again. i have updated the code.
my mic was not detecting sound, that's why some confusion happened. sorry for that !

**Comment by Mitushi-23** [comment]
> please check it again. i have updated the code. my mic was not detecting sound, that's why some confusion happened. sorry for that !

ok no problem.

**Pull request merged**
